steps:
- name: 'gcr.io/cloud-builders/ssh'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Save SSH key from Secret Manager
      echo "$CLOUDBUILD_SSH_KEY" > /root/.ssh/deploy_key
      chmod 600 /root/.ssh/deploy_key

      # SSH into VM and run deploy script
      ssh -i /root/.ssh/deploy_key -o StrictHostKeyChecking=no gopiguddeti1405@35.184.158.97"~/deploy.sh"

availableSecrets:
  secretManager:
    - versionName: "projects/web-app-311/secrets/cloudbuild_ssh_key/versions/1"
      env: ["CLOUDBUILD_SSH_KEY"]
