steps:
  - name: 'gcr.io/cloud-builders/ssh'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p ~/.ssh
        echo "$CLOUDBUILD_SSH_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no gopiguddeti1405@35.184.158.97 "~/deploy.sh"

availableSecrets:
  secretManager:
    - versionName: "projects/web-app-311/secrets/cloudbuild_ssh_key/versions/1"
      env: ["CLOUDBUILD_SSH_KEY"]
